---
# name: requirements.yml
# description: This file contains dependencies.
# author: while-true-do.io
# contact: hello@while-true-do.io
# license: BSD-3-Clause

# TODO: Edit or delete this file

- src: while_true_do.rpo_epel
