---
# tasks/main.yml for rsnapshot

- name: Manage rsnapshot Packages
  package:
    name: "{{ wtd_srv_rsnapshot_package }}"
    state: "{{ wtd_srv_rsnapshot_package_state }}"
  become: true
  tags:
    - rsnapshot
    - backup
    - package

- name: Manage rsnapshot Configuration
  template:
    src: "rsnapshot.conf.j2"
    dest: "/etc/rsnapshot.conf"
    owner: "root"
    group: "root"
    mode: 0644
    validate: "rsnapshot -c %s configtest"
  become: true
  tags:
    - rsnapshot
    - backup
    - configuration

# systemd scheduler
- name: Manage rsnapshot backup Service File
  template:
    src: "rsnapshot.service.j2"
    dest: "/etc/systemd/system/rsnapshot@.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  tags:
    - rsnapshot
    - backup
    - configuration
    - scheduler
    - service
    - systemd
    - timer

- name: Manage rsnapshot backup Timer File
  template:
    src: "rsnapshot.timer.j2"
    dest: "/etc/systemd/system/rsnapshot-{{ retain.name }}.timer"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  loop: "{{ wtd_srv_rsnapshot_conf.retains }}"
  loop_control:
    loop_var: retain
  tags:
    - rsnapshot
    - backup
    - configuration
    - scheduler
    - service
    - systemd
    - timer

- name: Manage rsnapshot backup Timer
  systemd:
    name: "rsnapshot-{{ retain.name }}.timer"
    state: "started"
    enabled: "{{ retain.enabled | default('true') }}"
    daemon_reload: true
  become: true
  loop: "{{ wtd_srv_rsnapshot_conf.retains }}"
  loop_control:
    loop_var: retain
  tags:
    - rsnapshot
    - backup
    - configuration
    - scheduler
    - service
    - systemd
    - timer
