---
- name: Converge
  hosts: all
  roles:
    # TODO: Provide a proper playbook, to test features of your role.
    - role: while_true_do.srv_rsnapshot
      wtd_rsnapshot_configs:
        - name: 'root'
          retains:
            - name: 'daily'
              time: '*-*-* 00:35'
              value: 7
            - name: 'weekly'
              time: 'Sun *-*-* 00:00'
              value: 4
            - name: 'monthly'
              time: '*-*-1 01:00'
              value: 2
          backups:
            - src: /root/doc
              target: localhost/root
            - src: /root/picture
              target: localhost/root
            - src: /root/videos
              target: localhost/root
          execStart: "/usr/bin/rsnapshot -c /etc/rsnapshot-root.conf %i"
        - name: 'user'
          retains:
            - name: 'daily'
              value: 7
          backups:
            - src: /home/user/doc
              target: localhost/user
            - src: /home/user/picture
              target: localhost/user
            - src: /home/user/videos
              target: localhost/user
          execStart: "/usr/bin/rsnapshot -c /etc/rsnapshot-user.conf %i"
